# Generated by Django 4.2.16 on 2024-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemode',
            name='place_city',
            field=models.CharField(default='city', max_length=200),
        ),
    ]
