# Generated by Django 4.2.16 on 2024-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placemode_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemode',
            name='place_city',
        ),
        migrations.RemoveField(
            model_name='placemode',
            name='place_name',
        ),
        migrations.AddField(
            model_name='placemode',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='State',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
