# Generated by Django 4.2.16 on 2024-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_placemode_place_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemode',
            name='Best_time_to_visit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Google_rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Significance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Time_needed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
