# Generated by Django 4.2.16 on 2024-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_placemode_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemode',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placemode',
            name='Zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
