# Generated by Django 5.1.1 on 2024-10-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_crowdmodel_placemode_image_url_placemode_crowd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemode',
            name='Image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
