# Generated by Django 5.1.1 on 2024-10-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_placemode_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdmodel',
            name='crowd_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crowdmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.placemode'),
        ),
        migrations.AddField(
            model_name='crowdmodel',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='crowdmodel',
            unique_together={('location', 'month')},
        ),
    ]
