# Generated by Django 5.1.1 on 2024-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_crowdmodel_crowd_count_crowdmodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdmodel',
            name='month_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
