# Generated by Django 5.1.5 on 2025-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemode',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
